//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Share.Properties {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Share.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Background {
            get {
                object obj = ResourceManager.GetObject("Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cookie {
            get {
                object obj = ResourceManager.GetObject("Cookie", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dort {
            get {
                object obj = ResourceManager.GetObject("Dort", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dortík {
            get {
                object obj = ResourceManager.GetObject("Dortík", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EnemyDoleva {
            get {
                object obj = ResourceManager.GetObject("EnemyDoleva", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EnemyDolůZleva {
            get {
                object obj = ResourceManager.GetObject("EnemyDolůZleva", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EnemyDolůZprava {
            get {
                object obj = ResourceManager.GetObject("EnemyDolůZprava", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EnemyDoprava {
            get {
                object obj = ResourceManager.GetObject("EnemyDoprava", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EnemyNahoruZleva {
            get {
                object obj = ResourceManager.GetObject("EnemyNahoruZleva", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EnemyNahoruZprava {
            get {
                object obj = ResourceManager.GetObject("EnemyNahoruZprava", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap High_Score_new {
            get {
                object obj = ResourceManager.GetObject("High_Score_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Icon podobný (Ikona).
        /// </summary>
        internal static System.Drawing.Icon Ikona__snyanke_cat_ {
            get {
                object obj = ResourceManager.GetObject("Ikona__snyanke_cat_", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Jahoda {
            get {
                object obj = ResourceManager.GetObject("Jahoda", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Lízátko {
            get {
                object obj = ResourceManager.GetObject("Lízátko", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nyan_cat_doleva {
            get {
                object obj = ResourceManager.GetObject("nyan_cat_doleva", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nyan_cat_dolů_zleva {
            get {
                object obj = ResourceManager.GetObject("nyan_cat_dolů_zleva", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nyan_cat_dolů_zprava {
            get {
                object obj = ResourceManager.GetObject("nyan_cat_dolů_zprava", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nyan_cat_doprava {
            get {
                object obj = ResourceManager.GetObject("nyan_cat_doprava", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nyan_cat_nahoru_zleva {
            get {
                object obj = ResourceManager.GetObject("nyan_cat_nahoru_zleva", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nyan_cat_nahoru_zprava {
            get {
                object obj = ResourceManager.GetObject("nyan_cat_nahoru_zprava", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pepermint {
            get {
                object obj = ResourceManager.GetObject("Pepermint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Reversed {
            get {
                object obj = ResourceManager.GetObject("Reversed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Stříbrná_hvězda {
            get {
                object obj = ResourceManager.GetObject("Stříbrná_hvězda", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Swap {
            get {
                object obj = ResourceManager.GetObject("Swap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Želé {
            get {
                object obj = ResourceManager.GetObject("Želé", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Zlatá_hvězda {
            get {
                object obj = ResourceManager.GetObject("Zlatá_hvězda", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Zmrzlina {
            get {
                object obj = ResourceManager.GetObject("Zmrzlina", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
